version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/letsFootball/src
    ports:
      - 3000:3000
    env_file:
      - ./.env

  backend-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'letsfootball'
      MYSQL_ROOT_PASSWORD: '1545'
      TZ: 'Asia/Seoul'
    ports:
      - 3306:3306
